name: Build Saltify (Windows)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Java
        shell: powershell
        run: |
          if (-not (Get-Command java -ErrorAction SilentlyContinue)) {
            Write-Host "Java not found, installing JDK 11..."
            choco install jdk11 -y
          } else {
            Write-Host "Java is already installed."
          }

      - name: Install NLTK
        run: |
          pip install nltk
          python -m nltk.downloader punkt

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller importlib-metadata sacremoses tokenizers
          pip install --upgrade transformers
          pip uninstall -y typing || true
          pip install git+https://github.com/Akascape/CTkXYFrame.git

      - name: Build EXE with PyInstaller
        run: >
          pyinstaller --name Saltify --windowed --noconfirm --onefile -c
          --copy-metadata torch
          --copy-metadata tqdm
          --copy-metadata regex
          --copy-metadata sacremoses
          --copy-metadata requests
          --copy-metadata packaging
          --copy-metadata filelock
          --copy-metadata numpy
          --copy-metadata tokenizers
          --copy-metadata importlib_metadata
          --collect-data sv_ttk
          --recursive-copy-metadata "openai-whisper"
          --collect-data whisper
          --collect-all CTkXYFrame
          GUI.py

      - name: Copy assets
        shell: cmd
        run: |
          robocopy build_assets dist/Saltify /e /v 
          mkdir dist\Saltify\_internal\lightning_fabric
          robocopy dist/Saltify/_internal/lightning dist/Saltify/_internal/lightning_fabric /e /v
          mkdir dist\Saltify\_internal\pattern\text\en\
          move dist/Saltify/en-model.slp dist/Saltify/_internal/pattern/text/en\

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: SpeechTranscription_windows
          path: dist/Saltify.exe
